### ISSUE TITLE
Add support for storing Events

### ISSUE THREAD

**Issue by hjarrell** [ufosc/club-backend-ex#4]
Add support for club events.

Events should at minimum store:

- Title
- Description
- Location
- Category
- Start DateTime
- End DateTime

Minimum tasks for this functionality (CRUD):
- [x] Create new Events
- [x] Get All Events
- [x] Get Specific Event
- [x] Update Event
- [x] Delete Event

Check out [this guide](https://github.com/ufosc/club-backend-ex/blob/develop/docs/DEVELOPING.md) for a tutorial.

Note: Don't worry about authentication/authorization for these those will be a separate issues while this project starts up

**Comment by annaraymaker** [comment]
lib # All the code for the project
├── club_backend # This is where the models + business logic is stored.  
│   ├── accounts
│   │   └── user.ex # Accounts "context" user model
│   ├── accounts.ex # Accounts "context" where logic + database interaction
│   ├── application.ex # Entry point of the application
│   ├── guardian.ex # JSON Web Tokens for session managment
│   └── repo.ex # Auto generated Ecto Repo code
├── club_backend.ex
├── club_backend_web
│   ├── channels # Future websocket/presence code
│   │   └── user_socket.ex
│   ├── controllers # Controllers for different routes
│   │   ├── auth_controller.ex
│   │   └── ping_controller.ex
│   ├── endpoint.ex
│   ├── gettext.ex
│   ├── router.ex # Definition of the HTTP routes
│   ├── telemetry.ex
│   └── views # Where the response is formatted
│       ├── auth_view.ex
│       ├── error_helpers.ex
│       └── error_view.ex
└── club_backend_web.ex
config # Central configuration
├── config.exs
├── dev.exs
├── prod.exs
├── prod.secret.exs
└── test.exs
priv
├── gettext # Localization
│   ├── en
│   │   └── LC_MESSAGES
│   │       └── errors.po
│   └── errors.pot
└── repo
    ├── migrations # Database changes
    │   └── 20200725220419_create_users.exs
    └── seeds.exs # Models to initialize in the database
test
├── club_backend
│   └── accounts_test.exs
├── club_backend_web
│   ├── channels
│   ├── controllers
│   └── views
│       └── error_view_test.exs
├── support
│   ├── channel_case.ex
│   ├── conn_case.ex
│   └── data_case.ex
└── test_helper.exs
